name: Install in conda env - windowz
on:
  push:
    paths:
    - '**.py'
    - '.github/workflows/thefirst-windows.yml'
    - 'env/fingeRNAt_env.yml'
    - 'tests/just_run.sh'
jobs:
  build:
    strategy:
      matrix:
        # os: ['ubuntu-18.04', 'ubuntu-20.04', 'macos-latest', 'windows-latest']
        os: ['windows-latest']
        # python-version: [3.5, 3.7, 3.8, 3.9]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.0.1
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          environment-file: env/fingeRNAt_env.yml
          activate-environment: fingernat
      - name: list packages
        shell: pwsh
        run: |
          conda list
      - name: run test
        shell: pwsh
        run: |
          conda env list
          cd tests
          python fingeRNAt_test.py
      - uses: actions/upload-artifact@v2
        with:
          name: outfiles
          path: tests/outputs/
          retention-days: 5
