name: CI (conda)
on:
  push:
    paths:
    - '**.py'
    - '.github/workflows/thefirst.yml'
jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        # os: ['ubuntu-latest']
        python-version: [3.5, 3.7, 3.8, 3.9]
        # python-version: [3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          environment-file: env/fingeRNAt_env.yml
          activate-environment: fingernat
      - name: run test
        shell: pwsh
        run: |
          conda env list
          cd tests
          python fingeRNAt_test.py
