name: CI (conda)
on:
  push:
    paths:
    - '**.py'
    - '.github/workflows/ubuntu-install.yml'
jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'ubuntu-20.04']
        # os: ['ubuntu-latest']
        # python-version: [3.5, 3.7, 3.8, 3.9]
        python-version: [3.8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install package
        run: |
          sudo apt-get update && sudo apt-get --no-install-recommends -y install openbabel python3.9-minimal python3-openbabel python3-pip python-is-python3 python3-pandas  python3-numpy python3-rdkit python3-tqdm python3-yaml
      - name: run test
        shell: pwsh
        run: |
          conda env list
          cd tests
          python fingeRNAt_test.py
