name: Ubuntu install from apt and pip
on:
  push:
    paths:
    - '**.py'
    - '.github/workflows/ubuntu-pip-install.yml'
jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install package
        run: |
          sudo apt-get update && sudo apt-get --no-install-recommends -y install openbabel python3.9-minimal python3-openbabel python3-pip python-is-python3
          pip install -r env/fingeRNAt_pip.txt
      - name: run test
        shell: pwsh
        run: |
          conda env list
          cd tests
          python fingeRNAt_test.py
